version: '3'

services:
  ui:
    build:
      context: ./ui/
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./ui/react-ui:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - 3000:3000